### ISSUE TITLE
Add TS typings to output/published library

### ISSUE THREAD

**Issue by joeyfigaro** [error-four-o-four/p5.utils#3]
Thank you for your work @error-four-o-four! Providing typings would make integrating the library in modern P5 setups a lot more user-friendly. If you're open to contributions, I'd be up for taking a stab at adding the typings and integrating them into the workflow for releasing new builds.

This would be especially helpful since you're overloading/changing the way `createCanvas` works.

**Comment by error-four-o-four** [comment]
Hey @joeyfigaro,
thank you for your interest.

I'm open for contributions, so feel free to create a pull request.

Well, I haven't set up a workflow yet but I could add eslint, prettier and lint-staged in advance. I'm also tempted to use vitejs/vite for a better development experience.

**Comment by error-four-o-four** [comment]
It's been a while @joeyfigaro ,
in case it still matters, I redid the library in TS and moved it to another repo: https://github.com/error-four-o-four/p5.qol.js.
This repo will be archived.
Ty

**Comment by joeyfigaro** [comment]
> It's been a while @joeyfigaro ,
> 
> in case it still matters, I redid the library in TS and moved it to another repo: https://github.com/error-four-o-four/p5.qol.js.
> 
> This repo will be archived.
> 
> Ty

Amazing! Thank you for the heads up. 🫡
